### ISSUE TITLE
Omissions in the `type.d.ts` file in the `Two.Path` module?

### ISSUE THREAD

**Issue by dickinson0718** [jonobr1/two.js#634]
I'm updating from `0.7.13` to `0.8.7` for my typescript application and I think that there are possibly some omissions in the `type.d.ts` file in the `Two.Path` module. 

1. The first issue is that I'm getting the error "Property 'closed' does not exist on type 'Path'" seen here

<img width="891" alt="Screen Shot 2022-05-27 at 2 04 06 PM" src="https://user-images.githubusercontent.com/9343855/170766218-49b80afb-9118-4609-bfd7-c25d8d176c4a.png">

this worked in `0.7.13` and I think that the current error stems from the fact that the file `type.d.ts` in the `Path` module 

<img width="786" alt="Screen Shot 2022-05-27 at 2 05 00 PM" src="https://user-images.githubusercontent.com/9343855/170766335-7d914150-9e94-4eec-9824-90953becd8d7.png">

doesn't include the `closed` property (like it does for `beginning`, `ending`, `fill`, `stroke`, etc).

2.  I'm trying to use a `RadialGradient` for a fill of a `Path` (just like I did in `0.7.13`) and I get the error of  
<img width="744" alt="Screen Shot 2022-05-27 at 2 50 53 PM" src="https://user-images.githubusercontent.com/9343855/170772770-df9aca06-968d-4e4b-84c2-cbb601df4dcb.png">

Again I think that the type for `Path.fill` should be more than just `string` in the `type.d.ts` file in the `Path` module

<img width="993" alt="Screen Shot 2022-05-27 at 2 51 55 PM" src="https://user-images.githubusercontent.com/9343855/170772900-93fb1570-d8ac-41d9-8b56-27979a8d9d50.png">

Shouldn't the type for `Path.fill` be `string` or `gradient` or `texture`?

3. I'm trying to scale a layer in a non-uniform way so I would like to assign `newLayer` as a vector (like I did in `0.7.13`) and the following tooltip seems to indicate is possible.

<img width="784" alt="Screen Shot 2022-05-27 at 3 59 56 PM" src="https://user-images.githubusercontent.com/9343855/170781769-10d46e70-90a4-4972-adc4-f5c296dffaed.png">

So shouldn't the type of `Shape.scale` be `number` or `vector`?

**Comment by jonobr1** [comment]
This is super helpful. Thank you! I'll try to address these all very soon.

**Comment by jonobr1** [comment]
Those changes are reflected in this branch: https://github.com/jonobr1/two.js/tree/issue-634-types

**Comment by jonobr1** [comment]
This is added to the latest npm package: https://www.npmjs.com/package/two.js

**Comment by dickinson0718** [comment]
@jonobr1 Thank you for your attention to this!
